title: Jannat Ara Meem # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   Ph.D. in Computer Science, University of California, Riverside
  <br><br>
  Research Focus: Information Retrieval (IR), Generative and Multimodal Question-Answering, LLMs and VLMs Reasoning
  <br><br>
  <a href="https://www.linkedin.com/in/jannat-ara-meem-197a0b165/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
